---
title: "checkerboard surfaces"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Produce graphics for figure 1: checkersurf.pdf

```{r, message=FALSE, echo=FALSE}
library(plot3D)
library(ks)
p <- 23
t <- 40
g <- 30
zmax <- 1.6
pdf("mathmag/checkersurf.pdf", width = 5, height = 3.2)
par(mfrow = c(2,3), mai = c(0.1,0,0,0))
rect3D(x0 = c(0,0), y0 = c(0.5,0), z0 = c(1.6, 0.4), 
       x1 = c(1,1), y1 = c(1, 0.5), z1 = NULL, 
       xlim = c(0,1), ylim=c(0,1), zlim = c(0,2),
       zlab = "", d=3, axes = FALSE, border="black", col="lightblue", phi = p, theta = t)
rect3D(x0 = rep(seq(0, 0.75, by = 0.25), 2), 
       y0 = c(rep(c(0.5,0),2), rep(c(0, 0.5), 2)),
       z0 = c(rep(1.6, 4), rep(0.4, 4)), 
       x1 = rep(seq(0.25, 1, by = 0.25), 2), 
       y1 = c(rep(c(1, 0.5), 2), rep(c(0.5, 1), 2)), 
       z1 = NULL, 
       xlim = c(0,1), ylim=c(0,1), zlim = c(0,2),
       zlab = "", d=3, axes = FALSE, border="black", col="lightblue", phi = p, theta = t)
rect3D(x0 = rep(seq(0, 0.875, by = 0.125), 4), 
       y0 = c(rep(c(0.75,0.5),4), rep(c(0.25, 0), 4), rep(c(0.5, 0.75), 4), rep(c(0,0.25), 4)),
       z0 = c(rep(1.6, 16), rep(0.4, 16)), 
       x1 = rep(seq(0.125, 1, by = 0.125), 4), 
       y1 = c(rep(c(1,0.75),4), rep(c(0.5, 0.25), 4), rep(c(0.75, 1), 4), rep(c(0.25,0.5), 4)),
       z1 = NULL, 
       xlim = c(0,1), ylim=c(0,1), zlim = c(0,2),
       zlab = "", d=3, axes = FALSE, border="black", col="lightblue", phi = p, theta = t)
#fudge <- 1.2 # Underfitting
fudge <- 0.5 # about right 
#fudge <- 0.7 # about right 
centroids <- cbind(rep(seq(1/16, 15/16, by = 1/8), 4), 
                       rep(seq(1/8,7/8,by=1/4), each=8))
abw <- Hns(centroids) * fudge
a.hat.kde <- kde(centroids, 
                 xmin = c(0,0), xmax = c(1,1), 
                 H = abw,
                 gridsize = c(g, g), 
                 w = c(rep(0.2, 16), rep(0.8, 16)))
a.hat <- list(x = a.hat.kde$eval.points[[1]], 
              y = a.hat.kde$eval.points[[2]], 
              z = a.hat.kde$estimate)
persp(a.hat,
       xlim = c(0,1), ylim=c(0,1), zlim = c(0,zmax),
       zlab = "", d=3, axes = FALSE, border="black", col="lightblue",  phi = p, theta = t)
a.hat.kde <- kde(centroids, 
                 xmin = c(0,0), xmax = c(1,1), 
                 H = abw,
                 gridsize = c(g, g), 
                 w = c(rep(c(0.2, 0.2, 0.8, 0.8), 4), rep(c(0.8,0.8,0.2,0.2), 4)))
a.hat <- list(x = a.hat.kde$eval.points[[1]], 
              y = a.hat.kde$eval.points[[2]], 
              z = a.hat.kde$estimate)
persp(a.hat,
       xlim = c(0,1), ylim=c(0,1), zlim = c(0,zmax),
       zlab = "", d=3, axes = FALSE, border="black", col="lightblue",  phi = p, theta = t)
a.hat.kde <- kde(centroids, 
                 xmin = c(0,0), xmax = c(1,1), 
                 H = abw,
                 gridsize = c(g, g), 
                 w = rep(c(rep(c(0.2, 0.8), 4), rep(c(0.8, 0.2), 4)), 2) )
a.hat <- list(x = a.hat.kde$eval.points[[1]], 
              y = a.hat.kde$eval.points[[2]], 
              z = a.hat.kde$estimate)
persp(a.hat,
       xlim = c(0,1), ylim=c(0,1), zlim = c(0.0,zmax),
       zlab = "", d=3, axes = FALSE, border="black", col="lightblue",  phi = p, theta = t)
dev.off()
```

## Compute S and G for all three checkerboard patterns.

```{r}
library(ks)
library(tidyverse)
if(!exists("grad", mode="function")) source("scripts/grad.R")
p <- 23
t <- 40
g <- 500
fudge <- 0.5 # about right 
#fudge <- 0.7 # about right 
centroids <- cbind(rep(seq(1/16, 15/16, by = 1/8), 4), 
                       rep(seq(1/8,7/8,by=1/4), each=8))
colnames(centroids) <- c("X","Y")

abw <- Hns(centroids) * fudge
u.hat.kde <- kde(centroids, 
                 xmin = c(0,0), xmax = c(1,1), 
                 H = abw,
                 gridsize = c(g, g) 
                 )
u.hat <- list(x = u.hat.kde$eval.points[[1]], 
              y = u.hat.kde$eval.points[[2]], 
              z = u.hat.kde$estimate)
a.hat.kde <- kde(centroids, 
                 xmin = c(0,0), xmax = c(1,1), 
                 H = abw,
                 gridsize = c(g, g), 
                 w = c(rep(0.2, 16), rep(0.8, 16)))
a.hat <- list(x = a.hat.kde$eval.points[[1]], 
              y = a.hat.kde$eval.points[[2]], 
              z = a.hat.kde$estimate)
b.hat.kde <- kde(centroids, 
                 xmin = c(0,0), xmax = c(1,1), 
                 H = abw,
                 gridsize = c(g, g), 
                 w = c(rep(0.8, 16), rep(0.2, 16)))
b.hat <- list(x = b.hat.kde$eval.points[[1]], 
              y = b.hat.kde$eval.points[[2]], 
              z = b.hat.kde$estimate)
Vint <- sum(pmin(a.hat$z, b.hat$z))/g^2
Vuni <- sum(pmax(a.hat$z, b.hat$z))/g^2
cat("S1 = ", 1-Vint/Vuni, "\n")

rok <- (u.hat.kde$estimate > 0.00000) # avoid dividing by zero
f.hat.kde <- u.hat.kde
f.hat.kde$estimate[rok] <- a.hat.kde$estimate[rok] / u.hat.kde$estimate[rok] * 1 / 2
f.hat <- list(x = f.hat.kde$eval.points[[1]],
              y = f.hat.kde$eval.points[[2]],
              z = f.hat.kde$estimate)
gr <- grad(f.hat, centroids[,1], centroids[,2])
magg <- sqrt(gr[1,]^2 + gr[2,]^2)
nmagg <- sum(!is.na(magg))
aveGrad <- mean(magg, na.rm = TRUE)
cat("G1 = ", atan(aveGrad)*2/pi, "\n")

border <- contourLines(f.hat, levels = 0.5)

borderdf <- list()
for(i in 1:length(border)){
  borderdf[[i]] <- data.frame(x = border[[i]]$x, y = border[[i]]$y)
}
cdf <- as_tibble(centroids)
cdf$w <- c(rep(0.2, 16), rep(0.8, 16))

cdf %>% ggplot() + geom_point(aes(x=X, y=Y,color=w)) -> p
for(i in seq(length(border))) {
  p <- p + geom_path(data=borderdf[[i]], aes(x=x, y=y), color="red3", size=1.0) 
}
p

allx <- do.call(c, lapply(border, function(l){l$x}))
ally <- do.call(c, lapply(border, function(l){l$y}))
gr <- grad(f.hat, allx, ally)
magg <- sqrt(gr[1,]^2 + gr[2,]^2)
nmagg <- sum(!is.na(magg))
aveGrad <- mean(magg, na.rm = TRUE)
cat("BG1 = ", atan(aveGrad)*2/pi, "\n")



a.hat.kde <- kde(centroids, 
                 xmin = c(0,0), xmax = c(1,1), 
                 H = abw,
                 gridsize = c(g, g), 
                 w = c(rep(c(0.2, 0.2, 0.8, 0.8), 4), rep(c(0.8,0.8,0.2,0.2), 4)))
a.hat <- list(x = a.hat.kde$eval.points[[1]], 
              y = a.hat.kde$eval.points[[2]], 
              z = a.hat.kde$estimate)
b.hat.kde <- kde(centroids, 
                 xmin = c(0,0), xmax = c(1,1), 
                 H = abw,
                 gridsize = c(g, g), 
                 w = c(rep(c(0.8, 0.8, 0.2, 0.2), 4), rep(c(0.2,0.2,0.8,0.8), 4)))
b.hat <- list(x = b.hat.kde$eval.points[[1]], 
              y = b.hat.kde$eval.points[[2]], 
              z = b.hat.kde$estimate)
Vint <- sum(pmin(a.hat$z, b.hat$z))/g^2
Vuni <- sum(pmax(a.hat$z, b.hat$z))/g^2
cat("S2 = ", 1-Vint/Vuni, "\n")

rok <- (u.hat.kde$estimate > 0.00000) # avoid dividing by zero
f.hat.kde <- u.hat.kde
f.hat.kde$estimate[rok] <- a.hat.kde$estimate[rok] / u.hat.kde$estimate[rok] * 1 / 2
f.hat <- list(x = f.hat.kde$eval.points[[1]],
              y = f.hat.kde$eval.points[[2]],
              z = f.hat.kde$estimate)
gr <- grad(f.hat, centroids[,1], centroids[,2])
magg <- sqrt(gr[1,]^2 + gr[2,]^2)
nmagg <- sum(!is.na(magg))
aveGrad <- mean(magg, na.rm = TRUE)
cat("G2 = ", atan(aveGrad)*2/pi, "\n")

border <- contourLines(f.hat, levels = 0.5)

borderdf <- list()
for(i in 1:length(border)){
  borderdf[[i]] <- data.frame(x = border[[i]]$x, y = border[[i]]$y)
}
cdf <- as_tibble(centroids)
cdf$w <- c(rep(c(0.2, 0.2, 0.8, 0.8), 4), rep(c(0.8,0.8,0.2,0.2), 4))

cdf %>% ggplot() + geom_point(aes(x=X, y=Y,color=w)) -> p
for(i in seq(length(border))) {
  p <- p + geom_path(data=borderdf[[i]], aes(x=x, y=y), color="red3", size=1.0) 
}
p

allx <- do.call(c, lapply(border, function(l){l$x}))
ally <- do.call(c, lapply(border, function(l){l$y}))
gr <- grad(f.hat, allx, ally)
magg <- sqrt(gr[1,]^2 + gr[2,]^2)
nmagg <- sum(!is.na(magg))
aveGrad <- mean(magg, na.rm = TRUE)
cat("BG2 = ", atan(aveGrad)*2/pi, "\n")

a.hat.kde <- kde(centroids, 
                 xmin = c(0,0), xmax = c(1,1), 
                 H = abw,
                 gridsize = c(g, g), 
                 w = rep(c(rep(c(0.2, 0.8), 4), rep(c(0.8, 0.2), 4)), 2) )
a.hat <- list(x = a.hat.kde$eval.points[[1]], 
              y = a.hat.kde$eval.points[[2]], 
              z = a.hat.kde$estimate)
b.hat.kde <- kde(centroids, 
                 xmin = c(0,0), xmax = c(1,1), 
                 H = abw,
                 gridsize = c(g, g), 
                 w = rep(c(rep(c(0.8, 0.2), 4), rep(c(0.2, 0.8), 4)), 2) )
b.hat <- list(x = b.hat.kde$eval.points[[1]], 
              y = b.hat.kde$eval.points[[2]], 
              z = b.hat.kde$estimate)
Vint <- sum(pmin(a.hat$z, b.hat$z))/g^2
Vuni <- sum(pmax(a.hat$z, b.hat$z))/g^2
cat("S3 = ", 1-Vint/Vuni, "\n")

rok <- (u.hat.kde$estimate > 0.00000) # avoid dividing by zero
f.hat.kde <- u.hat.kde
f.hat.kde$estimate[rok] <- a.hat.kde$estimate[rok] / u.hat.kde$estimate[rok] * 1 / 2
f.hat <- list(x = f.hat.kde$eval.points[[1]],
              y = f.hat.kde$eval.points[[2]],
              z = f.hat.kde$estimate)
gr <- grad(f.hat, centroids[,1], centroids[,2])
magg <- sqrt(gr[1,]^2 + gr[2,]^2)
nmagg <- sum(!is.na(magg))
aveGrad <- mean(magg, na.rm = TRUE)
cat("G3 = ", atan(aveGrad)*2/pi, "\n")

border <- contourLines(f.hat, levels = 0.5)

borderdf <- list()
for(i in 1:length(border)){
  borderdf[[i]] <- data.frame(x = border[[i]]$x, y = border[[i]]$y)
}
cdf <- as_tibble(centroids)
cdf$w <- rep(c(rep(c(0.2, 0.8), 4), rep(c(0.8, 0.2), 4)), 2) 

cdf %>% ggplot() + geom_point(aes(x=X, y=Y,color=w)) -> p
for(i in seq(length(border))) {
  p <- p + geom_path(data=borderdf[[i]], aes(x=x, y=y), color="red3", size=1.0) 
}
p

allx <- do.call(c, lapply(border, function(l){l$x}))
ally <- do.call(c, lapply(border, function(l){l$y}))
gr <- grad(f.hat, allx, ally)
magg <- sqrt(gr[1,]^2 + gr[2,]^2)
nmagg <- sum(!is.na(magg))
aveGrad <- mean(magg, na.rm = TRUE)
cat("BG3 = ", atan(aveGrad)*2/pi, "\n")

```

