---
title: "Comparison of income contours: 2013-2017"
author: "David J. Hunter"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(sf)
source("scripts/grad.R")
```


## Load data from files

These files can be generated using the scripts `get_acs_tractdata.R` and `countyStats.R`. Comment out year you don't want (2013 or 2017).

```{r}
all_block_geom <- readRDS("data/all_block_geom.rds") 
county_income <- readRDS("data/county_income.rds") 

#all_block_geom <- readRDS("data/all_block_geom13.rds") 
#county_income <- readRDS("data/county_income13.rds") 
```

## Read stored data

```{r, warning=FALSE}
fips <- "36061" # New York
fips <- "53033" # King County WA
fips <- "06071" # san bernardino
fips <- "35001" # bernalillo
fips <- "06037" # los angeles
fips <- "06083" # santa barbara
fips <- "06075" # san fransisco
fips <- "17043" # du page county IL
fips <- "17031" # cook county IL

fips <- "17031" # cook county IL
xmin <- -87.87
xmax <- -87.6
ymin <- 41.8
ymax <- 42.0

fips <- "06083" # santa barbara
#xmin <- -119.815
xmin <- -119.796
xmax <- -119.656
ymin <- 34.395
#ymax <- 34.465
ymax <- 34.454

fips <- "06075" # san fransisco
xmin <- -122.519
ymax <- 37.812
xmax <- -122.353
ymin <- 37.727

fips <- "53033" # King County WA (Seattle)

xmin <- -122.325
ymax <- 47.628
xmax <- -122.285
ymin <- 47.602

xmin <- -122.332
ymax <- 47.630
xmax <- -122.293
ymin <- 47.596

#maxBlockArea <- 15000000
maxBlockArea <- 150000000000
    cty <- 
      all_block_geom %>% filter(substr(GEOID,1,5) == fips)
    ctyMedian <- 
      county_income %>% filter(GEOID == fips) %>% .$B19013_001
    cty %>% mutate(
      centroid = suppressWarnings(st_centroid(geometry)),
      bgarea = as.numeric(st_area(geometry)),
      X = do.call(rbind, centroid)[, 1],
      Y = do.call(rbind, centroid)[, 2],
      aboveMed = (estimate > ctyMedian)
    ) %>%
      filter(bgarea < maxBlockArea) %>%
      filter(X < xmax & X > xmin) %>% # select rectangle width
      filter(Y > ymin & Y < ymax) -> # %>% # select rectangle height
   #   filter(!is.na(aboveMed)) ->
      cty
    cty %>% 
      dplyr::select(X, Y, aboveMed) ->
      allObs
    st_geometry(allObs) <- NULL
    allObs %>% filter(aboveMed) -> success
```

## Compute KDE and contours

```{r, warning=FALSE, message=FALSE}
library(ks)
aspect <- (max(allObs$X) - min(allObs$X))/(max(allObs$Y) - min(allObs$Y))
gsize <- c(round(200*aspect), 200)
support <- 3.7
fudge <- 0.4
abw <- Hpi(cbind(allObs$X,allObs$Y)) * fudge
sbw <- Hpi(cbind(success$X,success$Y)) * fudge
a.hat <- kde(cbind(allObs$X,allObs$Y), xmin=c(min(allObs$X), min(allObs$Y)), xmax=c(max(allObs$X), max(allObs$Y)), gridsize = gsize, supp = support, H = abw)
s.hat <- kde(cbind(success$X,success$Y), xmin=c(min(allObs$X), min(allObs$Y)), xmax=c(max(allObs$X), max(allObs$Y)), gridsize = gsize, supp = support, H = sbw)
f.hat.kde <- a.hat
rok <- (a.hat$estimate > 0.00001) # avoid dividing by zero
f.hat.kde$estimate[rok] <- s.hat$estimate[rok] / a.hat$estimate[rok] * nrow(success) / nrow(allObs)
f.hat <- list(x = f.hat.kde$eval.points[[1]],
              y = f.hat.kde$eval.points[[2]],
              z = f.hat.kde$estimate)
border <- contourLines(f.hat, levels = 0.5)

borderdf <- list()
for(i in 1:length(border)){
  # remove parts of contour that fall outside our region
  c <- st_union(cty$geometry)
  b <- cbind(border[[i]]$x, border[[i]]$y)
  pts <- st_sfc(lapply(seq(nrow(b)), function(j) {st_point(b[j,])}))
  st_crs(pts) <- st_crs(c)
  in_cty <- suppressMessages(st_intersects(pts, c, sparse = FALSE)[,1])
  border[[i]]$x[!in_cty] <- NA
  border[[i]]$y[!in_cty] <- NA
  borderdf[[i]] <- data.frame(x = border[[i]]$x, y = border[[i]]$y)
}
#cat("Found", length(border), "contours.\n")

#cty %>% filter(!is.na(aboveMed)) %>% ggplot() + geom_sf() + geom_point(aes(color=aboveMed,x=X, y=Y)) -> p
cty %>% filter(!is.na(aboveMed)) %>% ggplot() + geom_sf(aes(fill=aboveMed, geometry=geometry)) -> p
for(i in seq(length(border))) {
  p <- p + geom_path(data=borderdf[[i]], aes(x=x, y=y, size = lgrad(f.hat, x, y), color = lgrad(f.hat, x, y))) + scale_size(range = c(0.1, 3)) + scale_color_gradient(low="blue", high = "red")
}
p
```

## Get the street map

```{r, warning=FALSE, message=FALSE}
library(OpenStreetMap)
mp <- openmap(c(ymax,xmin),c(ymin,xmax), type="stamen-terrain")
mp.latlon <- openproj(mp, projection = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
```

# Street map only

```{r, warning=FALSE, message=FALSE}
q <- autoplot(mp.latlon) + labs(x = NULL, y = NULL) + 
  theme_void() +
  theme(legend.position = "none",plot.margin=grid::unit(c(0,0,0,0), "mm")) + coord_fixed(ratio=aspect)
q
```

## Plot on top of street map

```{r warning=FALSE, message=FALSE}
for(i in seq(length(border))) {
  q <- q + geom_path(data=borderdf[[i]], aes(x=x, y=y, size = lgrad(f.hat, x, y), color = lgrad(f.hat, x, y))) + scale_size(range = c(0.1, 5)) + scale_color_gradient(low="blue", high = "red")
}
# ggsave("monthly/chicago17.pdf", plot = q, width = 5.5, height = 4.1, units = "in")
#ggsave("monthly/chicago13.pdf", plot = q, width = 5.5, height = 4.1, units = "in")
q
```

## Save Plots as pdf

Comment out the year you don't want.

```{r, eval=FALSE}
#ggsave("monthly/sbincome13.pdf", plot = q + xlim(c(xmin+0.0019,xmax)) + ylim(c(ymin,ymax-0.01)), width = 5, height = 2.0, units = "in")
#ggsave("monthly/sbincome17.pdf", plot = q + xlim(c(xmin+0.0019,xmax)) + ylim(c(ymin,ymax-0.01)), width = 5, height = 2.0, units = "in")
ggsave("monthly/sfincome17.pdf", plot = q + xlim(c(xmin,xmax)) + ylim(c(ymin,ymax)), width = 5, height = 2.7, units = "in")
#ggsave("monthly/sfincome13.pdf", plot = q + xlim(c(xmin,xmax)) + ylim(c(ymin,ymax)), width = 5, height = 2.7, units = "in")
```

## Plot gradient as arrows

```{r}
gsz <- c(round(20*aspect), 20)
gfhat <- as_tibble(expand.grid(
  seq(min(allObs$X), max(allObs$X), length.out = gsz[1]),
  seq(min(allObs$Y), max(allObs$Y), length.out = gsz[2])[2:19]
))
names(gfhat) <- c("x", "y")
g <- grad(f.hat, gfhat$x, gfhat$y)
scl <- 0.0003 # scale factor for arrows
gfhat %>% 
  mutate(xend = x + g[1,]*scl, yend = y + g[2,]*scl) -> 
  gfhat
# Tag points that are outside the region
c <- st_union(cty$geometry)
b <- cbind(gfhat$x, gfhat$y)
pts <- st_sfc(lapply(seq(nrow(b)), function(j) {st_point(b[j,])}))
st_crs(pts) <- st_crs(c)
in_cty <- suppressMessages(st_intersects(pts, c, sparse = FALSE)[,1])

q <- autoplot(mp.latlon)
q <- q + labs(x = NULL, y = NULL) + 
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none")
q + geom_segment(data = gfhat[in_cty,], aes(x=x, y=y, xend=xend, yend=yend), arrow = arrow(angle = 25, length = unit(0.01, "npc")))
```

